{ StampVersion.Test — pins that scripts/stamp-version.pas, LWPT's own
  [prebuild] hook, is safe when several self-builds run it at once
  (issue #361).

  The script is copied into a scratch tool project (minus its InstantFPC
  shebang line) and compiled once with `lwpt build`, so every platform's
  toolchain configuration applies. The
  compiled copy then runs as several concurrent child processes against a
  scratch target project while this program keeps reading the generated
  include. Three assertions:

    1. Concurrent runs across changing versions all exit 0. Every read
       taken while they run sees the complete previous or new text, never
       a truncated or partial file; the final file holds exactly the new
       text, with SaveToFile's bytes (each line followed by LineEnding);
       and no temporary file remains beside it.
    2. Concurrent runs whose expected text is already present leave the
       file untouched: its modification time stays at a value set in the
       past.
    3. A target without a source/ directory fails without leaving any
       file behind. }

program StampVersion.Test;

{$mode delphi}{$H+}

uses
  Classes,
  Process,
  SysUtils,

  TestingPascalLibrary,
  Tests.LwptSubprocess,
  Tests.Scratch;

const
  SCRIPT_PATH = 'scripts/stamp-version.pas';
  INCLUDE_NAME = 'Version.inc';
  WRITER_COUNT = 6;
  ROUND_COUNT = 8;
  ROUND_TIMEOUT_MILLISECONDS = 120000;
  { A past modification time that no run can reproduce by rewriting. }
  PAST_AGE_DAYS = 2;

type
  TWriterResult = record
    ExitCode: Integer;
    Output: string;
  end;
  TWriterResults = array of TWriterResult;

  TStampVersionTest = class(TTestSuite)
  private
    FOrigDir, FScratch, FTool, FTarget, FStampExe: string;
    procedure WriteTargetManifest(const AVersion: string);
    function IncludePath: string;
    function ExpectedText(const AVersion: string): string;
    function SourceEntries: string;
    function RunWriters(const AAllowed: array of string;
      out AObservations, ATorn: Integer; out ATornSample: string)
      : TWriterResults;
    procedure ExpectWritersSucceeded(const AResults: TWriterResults);
  protected
    procedure BeforeAll; override;
    procedure AfterAll; override;
  public
    procedure SetupTests; override;
    procedure TestConcurrentRunsPublishCompleteText;
    procedure TestCurrentTextIsLeftUntouched;
    procedure TestMissingSourceDirectoryFailsCleanly;
  end;

{ Reads APath to its end in chunks. Unlike ReadBinaryFile it never trusts a
  size taken before the read, because an in-place writer can change the
  file between the two. }
function ReadWhileWritten(const APath: string): string;
var
  Stream: TFileStream;
  Chunk: array[0..4095] of Byte;
  Got, Have: Integer;
begin
  Result := '';
  Stream := TFileStream.Create(APath, fmOpenRead or fmShareDenyNone);
  try
    repeat
      Got := Stream.Read(Chunk, SizeOf(Chunk));
      if Got > 0 then
      begin
        Have := Length(Result);
        SetLength(Result, Have + Got);
        Move(Chunk, Result[Have + 1], Got);
      end;
    until Got <= 0;
  finally
    Stream.Free;
  end;
end;

procedure TStampVersionTest.BeforeAll;
var
  R: TLwptResult;
  Script: string;
begin
  FOrigDir := GetCurrentDir;
  SetLwptBinaryPath(ExpandFileName('build/lwpt'));
  FScratch := CreateScratchRoot('stamp-version');
  FTool := FScratch + '/tool';
  FTarget := FScratch + '/target';
  ForceDirectories(FTool);
  { InstantFPC skips the shebang line; the compiler does not. }
  Script := ReadBinaryFile(SCRIPT_PATH);
  if Copy(Script, 1, 2) = '#!' then
    Script := Copy(Script, Pos(#10, Script), MaxInt);
  WriteTextFile(FTool + '/stamp-version.pas', Script);
  WriteTextFile(FTool + '/lwpt.toml',
    '[package]'#10 +
    'name = "stamp-tool"'#10 +
    'version = "0.0.0"'#10 +
    ''#10 +
    '[build]'#10 +
    'stamp = { source = "stamp-version.pas", output = "build/stamp-version" }'#10);
  R := RunLwpt(['build'], FTool);
  DumpRunFailure('build stamp-version', R, 0);
  if R.ExitCode <> 0 then
    raise Exception.Create('could not compile ' + SCRIPT_PATH);
  FStampExe := ExpandFileName(ExpectedExe(FTool + '/build/stamp-version'));
end;

procedure TStampVersionTest.AfterAll;
begin
  SetCurrentDir(FOrigDir);
end;

procedure TStampVersionTest.WriteTargetManifest(const AVersion: string);
begin
  WriteTextFile(FTarget + '/lwpt.toml',
    '[package]'#10 +
    'name = "stamp-target"'#10 +
    'version = "' + AVersion + '"'#10);
end;

function TStampVersionTest.IncludePath: string;
begin
  Result := FTarget + '/source/' + INCLUDE_NAME;
end;

function TStampVersionTest.ExpectedText(const AVersion: string): string;
begin
  { TStringList.SaveToFile's bytes, which the script must keep. }
  Result :=
    '{ Auto-generated by scripts/stamp-version.pas. Do not hand-edit. }'
    + LineEnding
    + '{ Source: [package].version in lwpt.toml. }' + LineEnding
    + LineEnding
    + '  PROGRAM_VERSION = ''' + AVersion + ''';' + LineEnding;
end;

{ Every name in the target's source/ directory, sorted and comma-joined. }
function TStampVersionTest.SourceEntries: string;
var
  SR: TSearchRec;
  Names: TStringList;
begin
  Names := TStringList.Create;
  try
    Names.Sorted := True;
    if SysUtils.FindFirst(FTarget + '/source/*', faAnyFile, SR) = 0 then
    try
      repeat
        if (SR.Name <> '.') and (SR.Name <> '..') then Names.Add(SR.Name);
      until SysUtils.FindNext(SR) <> 0;
    finally
      SysUtils.FindClose(SR);
    end;
    Names.Delimiter := ',';
    Names.StrictDelimiter := True;
    Result := Names.DelimitedText;
  finally
    Names.Free;
  end;
end;

{ Starts WRITER_COUNT runs together and reads the include until they all
  exit. A read that is neither absent-by-sharing (Windows) nor one of
  AAllowed counts as torn. }
function TStampVersionTest.RunWriters(const AAllowed: array of string;
  out AObservations, ATorn: Integer; out ATornSample: string)
  : TWriterResults;
var
  Writers: array of TProcess;
  Index, Allowed: Integer;
  AnyRunning, Matched: Boolean;
  StartedAt: QWord;
  Seen: string;
begin
  AObservations := 0;
  ATorn := 0;
  ATornSample := '';
  SetLength(Result, WRITER_COUNT);
  SetLength(Writers, WRITER_COUNT);
  for Index := 0 to High(Writers) do Writers[Index] := nil;
  try
    for Index := 0 to High(Writers) do
    begin
      Writers[Index] := TProcess.Create(nil);
      Writers[Index].Executable := FStampExe;
      Writers[Index].CurrentDirectory := FTarget;
      Writers[Index].Options := [poUsePipes, poStderrToOutPut];
      { The release-tag override would change the expected text. }
      ConfigureProcessEnvironment(Writers[Index], ['LWPT_VERSION_OVERRIDE=']);
    end;
    for Index := 0 to High(Writers) do Writers[Index].Execute;

    StartedAt := GetTickCount64;
    repeat
      AnyRunning := False;
      for Index := 0 to High(Writers) do
        if Writers[Index].Running then AnyRunning := True;
      try
        Seen := ReadWhileWritten(IncludePath);
        Inc(AObservations);
        Matched := False;
        for Allowed := 0 to High(AAllowed) do
          if Seen = AAllowed[Allowed] then Matched := True;
        if not Matched then
        begin
          Inc(ATorn);
          if ATornSample = '' then
            ATornSample := Format('%d bytes: %s', [Length(Seen), Seen]);
        end;
      except
        on E: Exception do
        begin
          { A Windows reader can lose the race with a replacement and fail
            to open; a Unix rename never leaves the path absent. }
          {$IFNDEF MSWINDOWS}
          Inc(ATorn);
          if ATornSample = '' then ATornSample := 'read failed: ' + E.Message;
          {$ENDIF}
        end;
      end;
      {$IFDEF MSWINDOWS}
      { Let replacements land between reads. }
      Sleep(2);
      {$ENDIF}
      if GetTickCount64 - StartedAt > ROUND_TIMEOUT_MILLISECONDS then
        raise Exception.Create('stamp-version runs did not finish in time');
    until not AnyRunning;

    for Index := 0 to High(Writers) do
    begin
      Result[Index].Output := DrainAvailableStream(Writers[Index].Output);
      { Mirrors RunLwpt: trust ExitStatus when ExitCode claims success. }
      Result[Index].ExitCode := Writers[Index].ExitCode;
      if (Result[Index].ExitCode = 0) and (Writers[Index].ExitStatus <> 0) then
        Result[Index].ExitCode := Writers[Index].ExitStatus;
    end;
  finally
    for Index := 0 to High(Writers) do
    begin
      if Assigned(Writers[Index]) and Writers[Index].Running then
        Writers[Index].Terminate(1);
      Writers[Index].Free;
    end;
  end;
end;

procedure TStampVersionTest.ExpectWritersSucceeded(
  const AResults: TWriterResults);
var
  Index: Integer;
begin
  for Index := 0 to High(AResults) do
  begin
    if AResults[Index].ExitCode <> 0 then
      WriteLn(ErrOutput, 'stamp-version run ', Index, ' exited ',
        AResults[Index].ExitCode, ': ', AResults[Index].Output);
    Expect<Integer>(AResults[Index].ExitCode).ToBe(0);
  end;
end;

procedure TStampVersionTest.TestConcurrentRunsPublishCompleteText;
var
  Round, Observations, Torn, TotalObservations, TotalTorn: Integer;
  Previous, Current, TornSample, FirstTornSample: string;
  Results: TWriterResults;
begin
  RecursiveDelete(FTarget);
  ForceDirectories(FTarget + '/source');
  Previous := ExpectedText('1.0.0');
  WriteTextFile(IncludePath, Previous);
  TotalObservations := 0;
  TotalTorn := 0;
  FirstTornSample := '';
  for Round := 1 to ROUND_COUNT do
  begin
    WriteTargetManifest('1.0.' + IntToStr(Round));
    Current := ExpectedText('1.0.' + IntToStr(Round));
    Results := RunWriters([Previous, Current], Observations, Torn,
      TornSample);
    ExpectWritersSucceeded(Results);
    Inc(TotalObservations, Observations);
    Inc(TotalTorn, Torn);
    if FirstTornSample = '' then FirstTornSample := TornSample;
    Expect<string>(ReadBinaryFile(IncludePath)).ToBe(Current);
    Expect<string>(SourceEntries).ToBe(INCLUDE_NAME);
    Previous := Current;
  end;
  if TotalTorn <> 0 then
    WriteLn(ErrOutput, 'torn reads: ', TotalTorn, ' of ', TotalObservations,
      '; first: ', FirstTornSample);
  Expect<Boolean>(TotalObservations > 0).ToBe(True);
  Expect<Integer>(TotalTorn).ToBe(0);
end;

procedure TStampVersionTest.TestCurrentTextIsLeftUntouched;
var
  Observations, Torn: Integer;
  Past: LongInt;
  Current, TornSample: string;
  Results: TWriterResults;
begin
  RecursiveDelete(FTarget);
  ForceDirectories(FTarget + '/source');
  WriteTargetManifest('2.0.0');
  Current := ExpectedText('2.0.0');
  WriteTextFile(IncludePath, Current);
  Past := DateTimeToFileDate(Now - PAST_AGE_DAYS);
  Expect<Integer>(FileSetDate(IncludePath, Past)).ToBe(0);

  Results := RunWriters([Current], Observations, Torn, TornSample);
  ExpectWritersSucceeded(Results);
  Expect<Integer>(Torn).ToBe(0);
  Expect<Boolean>(Pos('already current', Results[0].Output) > 0).ToBe(True);
  Expect<LongInt>(FileAge(IncludePath)).ToBe(Past);
  Expect<string>(ReadBinaryFile(IncludePath)).ToBe(Current);
  Expect<string>(SourceEntries).ToBe(INCLUDE_NAME);
end;

procedure TStampVersionTest.TestMissingSourceDirectoryFailsCleanly;
var
  P: TProcess;
  ExitCode: Integer;
  SR: TSearchRec;
  Entries: Integer;
begin
  RecursiveDelete(FTarget);
  ForceDirectories(FTarget);
  WriteTargetManifest('3.0.0');
  P := TProcess.Create(nil);
  try
    P.Executable := FStampExe;
    P.CurrentDirectory := FTarget;
    P.Options := [poUsePipes, poStderrToOutPut, poWaitOnExit];
    ConfigureProcessEnvironment(P, ['LWPT_VERSION_OVERRIDE=']);
    P.Execute;
    ExitCode := P.ExitCode;
    if ExitCode = 0 then ExitCode := P.ExitStatus;
  finally
    P.Free;
  end;
  Expect<Boolean>(ExitCode <> 0).ToBe(True);
  { Only the manifest remains. }
  Entries := 0;
  if SysUtils.FindFirst(FTarget + '/*', faAnyFile, SR) = 0 then
  try
    repeat
      if (SR.Name <> '.') and (SR.Name <> '..') then Inc(Entries);
    until SysUtils.FindNext(SR) <> 0;
  finally
    SysUtils.FindClose(SR);
  end;
  Expect<Integer>(Entries).ToBe(1);
end;

procedure TStampVersionTest.SetupTests;
begin
  Test('concurrent runs across changing versions publish complete text '
    + 'and leave no temporary file', TestConcurrentRunsPublishCompleteText);
  Test('concurrent runs whose text is already present leave the file '
    + 'untouched', TestCurrentTextIsLeftUntouched);
  Test('a target without source/ fails without leaving files behind',
    TestMissingSourceDirectoryFailsCleanly);
end;

begin
  TestRunnerProgram.AddSuite(TStampVersionTest.Create(
    'stamp-version: concurrent runs'));
  TestRunnerProgram.Run;
  ExitCode := TestResultToExitCode;
end.
