#!/usr/bin/env instantfpc
program StampVersion;

{ Write source/Version.inc with a Pascal `PROGRAM_VERSION = '<value>';`
  constant. LWPT.Core.pas {$I}'s the result; lwpt --version reports it.

  The value is, in priority order:
    1. $LWPT_VERSION_OVERRIDE if set + non-empty — used by release.yml
       to stamp the GIT TAG into release binaries, so a downloaded
       release reports the version it was tagged as (e.g. `0.1.0-rc.3`).
    2. otherwise [package].version from lwpt.toml — the dev/unreleased
       version reported by locally-built binaries.

  This split is deliberate: dev builds report the manifest version
  (and Version.Test.pas's drift guard checks binary == manifest for
  those); release builds report the tag (release.yml asserts binary ==
  tag on the native target). See docs/ci.md "Release version stamping".

  Deliberately self-contained — does not depend on packages/toml so the
  bootstrap chicken-and-egg (lwpt cannot resolve its own deps before the
  binary exists) is preserved. The parser is a naive line scan for the
  first `version = "..."` line inside the [package] section; anything
  fancier (multi-section TOML state machine) would pull in packages/toml. }

{$mode delphi}{$H+}

uses
  Classes, SysUtils;

const
  MANIFEST_PATH = 'lwpt.toml';
  OUTPUT_PATH   = 'source/Version.inc';

function ExtractVersion(const ALines: TStringList): string;
var
  i, EqPos : Integer;
  Line, Trimmed, Value : string;
  InPackage : Boolean;
begin
  Result := '';
  InPackage := False;
  for i := 0 to ALines.Count - 1 do
  begin
    Trimmed := Trim(ALines[i]);
    if Trimmed = '' then Continue;
    if (Length(Trimmed) > 0) and (Trimmed[1] = '#') then Continue;

    if (Length(Trimmed) >= 2) and (Trimmed[1] = '[') then
    begin
      InPackage := SameText(Trimmed, '[package]');
      Continue;
    end;

    if not InPackage then Continue;

    Line := Trimmed;
    if not SameText(Copy(Line, 1, 7), 'version') then Continue;

    EqPos := Pos('=', Line);
    if EqPos = 0 then Continue;

    Value := Trim(Copy(Line, EqPos + 1, MaxInt));
    Value := StringReplace(Value, '"', '', [rfReplaceAll]);
    Value := StringReplace(Value, '''', '', [rfReplaceAll]);
    Result := Trim(Value);
    Exit;
  end;
end;

var
  Lines  : TStringList;
  Version, Override_, SourceNote: string;
  Out    : TStringList;
begin
  try
    Override_ := Trim(GetEnvironmentVariable('LWPT_VERSION_OVERRIDE'));
    if Override_ <> '' then
    begin
      Version := Override_;
      SourceNote := '$LWPT_VERSION_OVERRIDE (release tag)';
    end
    else
    begin
      if not FileExists(MANIFEST_PATH) then
      begin
        WriteLn(ErrOutput, 'stamp-version: ', MANIFEST_PATH,
          ' not found (run from repo root)');
        Halt(1);
      end;

      Lines := TStringList.Create;
      try
        Lines.LoadFromFile(MANIFEST_PATH);
        Version := ExtractVersion(Lines);
      finally
        Lines.Free;
      end;

      if Version = '' then
      begin
        WriteLn(ErrOutput, 'stamp-version: no `version` field in [package] of ',
          MANIFEST_PATH);
        Halt(1);
      end;
      SourceNote := '[package].version in ' + MANIFEST_PATH;
    end;

    Out := TStringList.Create;
    try
      Out.Add('{ Auto-generated by scripts/stamp-version.pas. Do not hand-edit. }');
      Out.Add('{ Source: ' + SourceNote + '. }');
      Out.Add('');
      Out.Add('  PROGRAM_VERSION = ' + QuotedStr(Version) + ';');
      Out.SaveToFile(OUTPUT_PATH);
    finally
      Out.Free;
    end;

    WriteLn('stamp-version: wrote ', OUTPUT_PATH, ' = ', Version,
      ' (from ', SourceNote, ')');
  except
    on E: Exception do
    begin
      WriteLn(ErrOutput, 'stamp-version: ', E.Message);
      Halt(1);
    end;
  end;
end.
