{ LWPT.Command.Init — init subcommand entrypoint. }
unit LWPT.Command.Init;

{$I Shared.inc}
{$J-}
{$modeswitch nestedcomments+}

interface

procedure CmdInit(AYes, AForce, AAdopt: Boolean);

implementation

uses
  Classes,
  SysUtils,

  CLI.Prompts,
  LWPT.BuildSession,
  LWPT.Command.Build,
  LWPT.Command.Install,
  LWPT.Core,
  LWPT.Manifest,
  LWPT.WorkerBudget;

const
  DEFAULT_VERSION    = '0.1.0';
  DEFAULT_SOURCE_DIR = 'source';
  DEFAULT_BUILD_DIR  = 'build';

{
  CmdInit (ADR-0010) — scaffold a new LWPT project or adopt the
  missing scaffold around an existing manifest. Fresh init is
  interactive by default; --yes (-y) uses defaults derived from the
  CWD's basename (npm-init-y style). It refuses to overwrite an
  existing lwpt.toml unless --force is also passed. Adoption preserves
  that manifest and is therefore mutually exclusive with --force.
  =========================================================================== }
procedure WriteScaffoldManifest(const APath, AName, AVersion,
  ASourceDir, ABuildDir, AEntryName: string);
var SL: TStringList;
begin
  SL := TStringList.Create;
  try
    SL.Add('# ' + PROGRAM_NAME + '.toml — generated by `' + PROGRAM_NAME
           + ' init`. Edit me.');
    SL.Add('');
    SL.Add('[package]');
    SL.Add('name = "' + AName + '"');
    SL.Add('version = "' + AVersion + '"');
    SL.Add('units = ["' + ASourceDir + '"]');
    SL.Add('');
    SL.Add('[build]');
    SL.Add(AEntryName + ' = { source = "' + ASourceDir + '/'
           + AEntryName + '.pas", output = "' + ABuildDir + '/'
           + AEntryName + '" }');
    SL.Add('');
    SL.Add('# [dependencies]');
    SL.Add('# horse = "HashLoad/horse@^4.0.0"               # GitHub by default');
    SL.Add('# ci-debug = "gitlab:gitlab-examples/ci-debug-trace@dd648b2e48ce6518303b0bb580b2ee32fadaf045"');
    SL.Add('# leaf = "../leaf"                               # local path');
    SL.Add('# See ADR-0009 for the full source-spec syntax.');
    SL.Add('');
    SL.Add('# [sources]   — custom git-host prefixes; see ADR-0009.');
    SL.Add('# gitea = { archive = "https://git.example.com/{user}/{repository}/archive/{ref}.tar.gz", git = "https://git.example.com/{user}/{repository}.git" }');
    SL.SaveToFile(APath);
  finally
    SL.Free;
  end;
end;

{ Package names + entry names follow LWPT's project-name grammar, while
  `program X;` must be a Pascal identifier. The filename + entry name +
  greeting text keep the original spelling — FPC doesn't require the
  program name to match the filename, so this stays out of the user's way. }
function SanitisePascalIdent(const S: string): string;
var i: Integer;
begin
  Result := '';
  for i := 1 to Length(S) do
    if (S[i] in ['a'..'z']) or (S[i] in ['A'..'Z'])
       or (S[i] in ['0'..'9']) or (S[i] = '_') then
      Result := Result + S[i]
    else
      Result := Result + '_';
  if Result = '' then
    Result := '_';
  if Result[1] in ['0'..'9'] then
    Result := '_' + Result;
end;

procedure WriteHelloProgram(const APath, AEntryName: string);
var SL: TStringList;
begin
  ForceDirectories(ExtractFileDir(APath));
  SL := TStringList.Create;
  try
    SL.Add('program ' + SanitisePascalIdent(AEntryName) + ';');
    SL.Add('');
    SL.Add('{$mode delphi}{$H+}');
    SL.Add('');
    SL.Add('begin');
    SL.Add('  WriteLn(''hello from ' + AEntryName + ''');');
    SL.Add('end.');
    SL.SaveToFile(APath);
  finally
    SL.Free;
  end;
end;

procedure AppendText(const APath, AText: string; AExisting: Boolean);
var
  Stream: TFileStream;
  Mode: Word;
begin
  if AText = '' then Exit;
  if AExisting then Mode := fmOpenReadWrite or fmShareDenyWrite
  else Mode := fmCreate;
  Stream := TFileStream.Create(APath, Mode);
  try
    Stream.Seek(0, soEnd);
    Stream.WriteBuffer(AText[1], Length(AText));
  finally
    Stream.Free;
  end;
end;

procedure ValidateWritePath(const AProjectRoot, APath,
  ADescription: string);
var
  RootPath, CurrentPath, ParentPath: string;
begin
  RootPath := ExcludeTrailingPathDelimiter(ExpandFileName(AProjectRoot));
  CurrentPath := ExcludeTrailingPathDelimiter(ExpandFileName(APath));
  if not PathContains(RootPath, CurrentPath) then
    raise EManifestError.CreateFmt(
      'refusing to create %s outside %s', [ADescription, AProjectRoot]);

  while PathContains(RootPath, CurrentPath) do
  begin
    if IsDirSymlinkOrJunction(CurrentPath) then
      raise EManifestError.CreateFmt(
        'refusing to write %s through symlink or junction "%s"',
        [ADescription, CurrentPath]);
    if PathContains(CurrentPath, RootPath) then Break;
    ParentPath := ExtractFileDir(CurrentPath);
    if ParentPath = CurrentPath then Break;
    CurrentPath := ParentPath;
  end;
end;

procedure EnsureGitignoreEntries(const APath: string;
  const ABuildDirs: array of string; AReport: Boolean);
var
  Wanted: TStringArray;
  Missing: array of Boolean;
  SL: TStringList;
  i, j: Integer;
  Existed, HasEntry, NeedsLineEnding: Boolean;
  Appendix: string;
  Stream: TFileStream;
  LastByte: Byte;
begin
  SetLength(Wanted, 4 + Length(ABuildDirs));
  Wanted[0] := GITIGNORE_LINE;
  Wanted[1] := INSTALL_LOCK;
  Wanted[2] := BUILD_SESSIONS_DIR + '/';
  Wanted[3] := WORKER_STATE_FALLBACK_DIR + '/';
  for i := 0 to High(ABuildDirs) do
    Wanted[4 + i] := StringReplace(
      IncludeTrailingPathDelimiter(ABuildDirs[i]),
      DirectorySeparator, '/', [rfReplaceAll]);
  Existed := FileExists(APath);
  SetLength(Missing, Length(Wanted));
  SL := TStringList.Create;
  try
    if Existed then SL.LoadFromFile(APath);
    Appendix := '';
    NeedsLineEnding := False;
    if Existed then
    begin
      Stream := TFileStream.Create(APath, fmOpenRead or fmShareDenyNone);
      try
        if Stream.Size > 0 then
        begin
          Stream.Seek(-1, soEnd);
          Stream.ReadBuffer(LastByte, 1);
          NeedsLineEnding := not (LastByte in [10, 13]);
        end;
      finally
        Stream.Free;
      end;
    end
    else
      Appendix := '# generated by `' + PROGRAM_NAME + ' init`'
        + LineEnding;

    for i := 0 to High(Wanted) do
    begin
      HasEntry := False;
      for j := 0 to SL.Count - 1 do
        if Trim(SL[j]) = Wanted[i] then begin HasEntry := True; Break; end;
      if not HasEntry then
      begin
        Missing[i] := True;
        if NeedsLineEnding then
        begin
          Appendix := Appendix + LineEnding;
          NeedsLineEnding := False;
        end;
        Appendix := Appendix + Wanted[i] + LineEnding;
      end;
    end;
    AppendText(APath, Appendix, Existed);
    if AReport then
      for i := 0 to High(Wanted) do
        if Missing[i] then
          WriteLn('  added .gitignore entry ', Wanted[i])
        else
          WriteLn('  found .gitignore entry ', Wanted[i]);
  finally
    SL.Free;
  end;
end;

procedure AddBuildOutputDirectory(const AProjectRoot, AOutput: string;
  var ABuildDirs: TStringArray);
var
  RootPath, OutputDir, RelativeDir: string;
  i, Count: Integer;
begin
  OutputDir := ExtractFileDir(Trim(AOutput));
  if OutputDir = '' then Exit;

  RootPath := ExcludeTrailingPathDelimiter(ExpandFileName(AProjectRoot));
  OutputDir := ExcludeTrailingPathDelimiter(ExpandFileName(OutputDir));
  if not PathContains(RootPath, OutputDir)
     or PathContains(OutputDir, RootPath) then Exit;

  RelativeDir := Copy(OutputDir, Length(RootPath) + 2, MaxInt);
  RelativeDir := StringReplace(RelativeDir, DirectorySeparator, '/',
    [rfReplaceAll]);
  for i := 0 to High(ABuildDirs) do
    if ABuildDirs[i] = RelativeDir then Exit;

  Count := Length(ABuildDirs);
  SetLength(ABuildDirs, Count + 1);
  ABuildDirs[Count] := RelativeDir;
end;

procedure AdoptExistingProject(const ACWD: string);
var
  Man: TManifest;
  UnitPaths, BuildDirs: TStringArray;
  UnitDir: string;
  i: Integer;
begin
  if not FileExists(MANIFEST_FILE) then
    raise EManifestError.CreateFmt(
      'cannot adopt without an existing %s in %s',
      [MANIFEST_FILE, ACWD]);
  if DirectoryExists('.gitignore') then
    raise EManifestError.Create(
      'cannot update .gitignore because that path is a directory');
  ValidateWritePath(ACWD, ExpandFileName('.gitignore'), '.gitignore');

  Man := LoadManifest(MANIFEST_FILE);
  SetLength(UnitPaths, Length(Man.Units));
  for i := 0 to High(Man.Units) do
  begin
    if Trim(Man.Units[i]) = '' then
      raise EManifestError.Create(
        '[package].units contains an empty directory path');
    UnitPaths[i] := ExpandFileName(Man.Units[i]);
    if FileExists(UnitPaths[i]) then
      raise EManifestError.CreateFmt(
        '[package].units path "%s" is a file, not a directory',
        [Man.Units[i]]);
    if not DirectoryExists(UnitPaths[i]) then
      ValidateWritePath(ACWD, UnitPaths[i],
        '[package].units path "' + Man.Units[i] + '"');
  end;
  for i := 0 to High(Man.BuildEntries) do
    AddBuildOutputDirectory(ACWD, Man.BuildEntries[i].Output, BuildDirs);
  if Length(BuildDirs) = 0 then
  begin
    SetLength(BuildDirs, 1);
    BuildDirs[0] := DEFAULT_BUILD_DIR;
  end;

  WriteLn('adopting existing ', PROJECT_NAME, ' project in ', ACWD);
  WriteLn('  preserved ', MANIFEST_FILE);
  for i := 0 to High(UnitPaths) do
  begin
    UnitDir := Man.Units[i];
    if DirectoryExists(UnitPaths[i]) then
      WriteLn('  found unit directory ', UnitDir)
    else
    begin
      if not ForceDirectories(UnitPaths[i])
         or not DirectoryExists(UnitPaths[i]) then
        raise EManifestError.CreateFmt(
          'failed to create [package].units directory "%s"', [UnitDir]);
      WriteLn('  created unit directory ', UnitDir);
    end;
  end;
  EnsureGitignoreEntries('.gitignore', BuildDirs, True);
end;

{ ValidPackageName lives in LWPT.Manifest — the package-name grammar
  shared with `lwpt add`'s name validation and the installer's
  prune guard. }

procedure CmdInit(AYes, AForce, AAdopt: Boolean);
var
  Name, Version, SourceDir, BuildDir, EntryName, CWD, EntryPath: string;
begin
  CWD := GetCurrentDir;
  if AAdopt then
  begin
    if AForce then
      raise EManifestError.Create(
        '--adopt and --force cannot be used together');
    AdoptExistingProject(CWD);
    Exit;
  end;

  if FileExists(MANIFEST_FILE) and not AForce then
    raise EManifestError.CreateFmt(
      '%s already exists in %s. Pass --force to overwrite, or '
      + 'remove the file first if you really mean to re-init.',
      [MANIFEST_FILE, CWD]);

  { Defaults derived from the CWD basename. Stripping a trailing
    path delimiter handles "/Users/foo/myproj/" → "myproj". }
  Name := ExtractFileName(ExcludeTrailingPathDelimiter(CWD));
  if (Name = '') or not ValidPackageName(Name) then Name := 'lwpt-project';
  Version   := DEFAULT_VERSION;
  SourceDir := DEFAULT_SOURCE_DIR;
  BuildDir  := DEFAULT_BUILD_DIR;
  EntryName := Name;

  if not AYes then
  begin
    WriteLn('initialising new ', PROJECT_NAME, ' project in ', CWD);
    WriteLn('press <enter> to accept the default in parentheses.');
    WriteLn;
    Name      := ReadPromptLine('package name',        Name);
    if not ValidPackageName(Name) then
      raise EManifestError.CreateFmt(
        'package name "%s" is not a valid identifier (must be ASCII '
        + 'letters/digits/hyphen/underscore)', [Name]);
    Version   := ReadPromptLine('version',             Version);
    SourceDir := ReadPromptLine('source folder',       SourceDir);
    BuildDir  := ReadPromptLine('build folder',        BuildDir);
    { Entry name default tracks the (possibly edited) package name —
      if you typed a new name in the first prompt, the entry should
      follow unless explicitly overridden. }
    if EntryName <> Name then EntryName := Name;
    EntryName := ReadPromptLine('project entry name',  EntryName);
    if not ValidPackageName(EntryName) then
      raise EManifestError.CreateFmt(
        'entry name "%s" is not a valid identifier (must be ASCII '
        + 'letters/digits/hyphen/underscore)', [EntryName]);
  end;

  EntryPath := SourceDir + '/' + EntryName + '.pas';
  WriteScaffoldManifest(MANIFEST_FILE, Name, Version,
    SourceDir, BuildDir, EntryName);
  WriteHelloProgram(EntryPath, EntryName);
  EnsureGitignoreEntries('.gitignore', [BuildDir], False);

  WriteLn;
  WriteLn('initialized ', Name, ' v', Version);
  WriteLn('  ', MANIFEST_FILE, '   (manifest)');
  WriteLn('  ', EntryPath,     '   (hello-world entry)');
  WriteLn('  .gitignore       (entries appended)');
  WriteLn;

  { Post-init install + build chain. Interactive mode prompts (Y
    default) before running them so the user can opt out; --yes
    SKIPS the prompt + skips the actions (just the scaffold, the
    user runs install/build themselves). The lockfile is created
    by `lwpt install`, not by init — no need for an empty stub. }
  if AYes then
  begin
    WriteLn('next: `', PROGRAM_NAME, ' install` then `',
            PROGRAM_NAME, ' build` to fetch deps + compile.');
    Exit;
  end;

  if PromptYesNo('run `' + PROGRAM_NAME + ' install` and `'
    + PROGRAM_NAME + ' build` now?', True) then
  begin
    WriteLn;
    WriteLn('--- ', PROGRAM_NAME, ' install ---');
    CmdInstall(MANIFEST_FILE, False);
    WriteLn;
    WriteLn('--- ', PROGRAM_NAME, ' build ---');
    CmdBuild(MANIFEST_FILE, [], False, False, 0);
    WriteLn;
    WriteLn('Run ./', BuildDir, '/', EntryName, ' to try it.');
  end
  else
    WriteLn('skipped install + build. Run `', PROGRAM_NAME,
            ' install` then `', PROGRAM_NAME, ' build` when ready.');
end;

end.
